import {
  extractImageTextWithGemini,
  structureWithGemini,
} from "./gemini-service.js";
import { normalizeWhitespace, toSentenceCase } from "./text-utils.js";

const ALLOWED_BLOCKS = new Set(["heading", "subheading", "paragraph", "bullet"]);
const BULLET_PREFIX_PATTERN =
  /^([\u2022\-*]|[0-9]+[.)]|\([0-9]+\)|[A-Za-z][.)]|[ivxlcdm]+[.)]|\([A-Za-z]{1,6}\)|[\u2192\u21d2\u27a4\u27a6\u27f6\u25b8\u25ba])\s+/i;
const SECTION_NUMBER_PATTERN = /^((?:\d+\.)*\d+)(?:[.)])?\s+/;
const ROMAN_HEADING_PATTERN = /^(?:[IVXLCDM]+[.)])\s+/i;
const LABEL_HEADING_PATTERN =
  /^(?:why|what|how|when|where|example|problem|definition|formula|algorithm|approach|observation|advantage|advantages|drawback|drawbacks|summary|overview|steps?|case(?:-\d+)?|applications?|complexity|intuition|dry run|pseudocode|proof)\b/i;
const CODE_LIKE_PATTERN =
  /[#{};<>]|(?:\b(?:int|float|double|char|void|return|printf|scanf)\b|for\s*\(|while\s*\()/;
const MAX_PARAGRAPH_CHARS = 280;
const MAX_BULLET_CHARS = 220;

function normalizeCompareText(text) {
  return normalizeWhitespace(text).toLowerCase().replace(/[^\w]+/g, " ").trim();
}

function looksAutoGeneratedTitle(text) {
  const clean = normalizeWhitespace(text);
  if (!clean) {
    return true;
  }

  const compact = clean.replace(/[\s_-]+/g, "");
  if (compact.length >= 16 && /^[a-f0-9]+$/i.test(compact)) {
    return true;
  }

  if (!/\s/.test(clean) && compact.length >= 18 && /^[A-Za-z0-9]+$/.test(compact)) {
    return true;
  }

  if (/^(document|scan|image|img|photo|untitled)[-_ ]*\d*$/i.test(clean)) {
    return true;
  }

  return false;
}

function getWordCount(text) {
  return normalizeWhitespace(text).split(/\s+/).filter(Boolean).length;
}

function getUpperRatio(text) {
  const clean = String(text || "");
  return clean.replace(/[^A-Z]/g, "").length / Math.max(1, clean.length);
}

function getSectionDepth(text) {
  const match = normalizeWhitespace(text).match(SECTION_NUMBER_PATTERN);
  if (!match?.[1]) {
    return 0;
  }

  return match[1].split(".").filter(Boolean).length;
}

function looksCodeLike(text) {
  return CODE_LIKE_PATTERN.test(normalizeWhitespace(text));
}

function isLikelyCenteredLine(line, page) {
  const pageCenter = page.width / 2;
  const lineCenter = (line.x + line.endX) / 2;
  return Math.abs(lineCenter - pageCenter) <= page.width * 0.14;
}

function classifyHeadingText(text, profile, options = {}) {
  const clean = normalizeWhitespace(text);
  if (!clean || looksCodeLike(clean) || clean.length > 140) {
    return "";
  }

  const wordCount = getWordCount(clean);
  const upperRatio = getUpperRatio(clean);
  const endsWithColon = /:\s*$/.test(clean);
  const endsWithQuestion = /\?\s*$/.test(clean);
  const startsLowercase = /^[a-z]/.test(clean);
  const sectionDepth = getSectionDepth(clean);
  const numbered = Boolean(sectionDepth) || ROMAN_HEADING_PATTERN.test(clean);
  const labelLike = LABEL_HEADING_PATTERN.test(clean);
  const strongTypography = Boolean(options.largeText);
  const centered = Boolean(options.centered);
  const shortWordLimit = profile.heuristics.shortHeadingMaxWords + (numbered ? 10 : 2);
  const shortHeading = wordCount <= shortWordLimit;

  if (startsLowercase && !numbered) {
    return "";
  }

  const looksHeading =
    numbered ||
    centered ||
    (shortHeading &&
      (strongTypography ||
        labelLike ||
        upperRatio > 0.45 ||
        endsWithColon ||
        endsWithQuestion));

  if (!looksHeading) {
    return "";
  }

  if (
    sectionDepth >= 3 ||
    (!numbered && (labelLike || endsWithColon || endsWithQuestion))
  ) {
    return "subheading";
  }

  return "heading";
}

function classifyHeadingLine(line, page, profile) {
  return classifyHeadingText(line.text, profile, {
    centered: isLikelyCenteredLine(line, page) && line.y >= page.height * 0.72,
    largeText:
      line.isBold || line.fontSize >= profile.typography.headingSize - 0.45,
  });
}

function isLikelyBullet(text) {
  return BULLET_PREFIX_PATTERN.test(text.trim());
}

function extractListItem(text) {
  const clean = normalizeWhitespace(text);
  const match = clean.match(BULLET_PREFIX_PATTERN);
  if (!match) {
    return {
      marker: "",
      text: clean,
    };
  }

  return {
    marker: normalizeWhitespace(match[1]),
    text: clean.slice(match[0].length).trim(),
  };
}

function splitTextIntoChunks(text, maxChars) {
  const clean = normalizeWhitespace(text);
  if (!clean || clean.length <= maxChars) {
    return clean ? [clean] : [];
  }

  const sentences = clean.split(/(?<=[.?!;])\s+(?=[A-Z0-9(])/);
  if (sentences.length < 2) {
    return [clean];
  }

  const chunks = [];
  let current = "";

  for (const sentence of sentences) {
    const nextValue = current ? `${current} ${sentence}` : sentence;
    if (current && nextValue.length > maxChars) {
      chunks.push(current);
      current = sentence;
      continue;
    }

    current = nextValue;
  }

  if (current) {
    chunks.push(current);
  }

  return chunks;
}

function postProcessBlocks(blocks, profile) {
  const processed = [];

  for (const block of blocks || []) {
    if (block?.type === "image") {
      processed.push(block);
      continue;
    }

    const cleanText = normalizeWhitespace(block?.text);
    if (!cleanText) {
      continue;
    }

    let type = ALLOWED_BLOCKS.has(block?.type) ? block.type : "paragraph";
    let text = cleanText;
    let marker = normalizeWhitespace(block?.marker);

    if (isLikelyBullet(text)) {
      const listItem = extractListItem(text);
      type = "bullet";
      text = listItem.text;
      marker = listItem.marker;
    } else if (type !== "bullet") {
      const inferredHeadingType = classifyHeadingText(text, profile, {
        largeText: type === "heading" || type === "subheading",
      });

      if (inferredHeadingType) {
        type = inferredHeadingType;
      }
    }

    if (processed.length) {
      const previousBlock = processed.at(-1);
      if (
        previousBlock.type !== "image" &&
        previousBlock.type === type &&
        normalizeCompareText(`${previousBlock.marker || ""} ${previousBlock.text}`) ===
          normalizeCompareText(`${marker || ""} ${text}`)
      ) {
        continue;
      }
    }

    if (type === "paragraph" || type === "bullet") {
      const maxChars = type === "bullet" ? MAX_BULLET_CHARS : MAX_PARAGRAPH_CHARS;
      const chunks = splitTextIntoChunks(text, maxChars);

      if (!chunks.length) {
        continue;
      }

      for (const chunk of chunks) {
        processed.push({
          type,
          text: chunk,
          ...(type === "bullet" && marker ? { marker } : {}),
        });
      }

      continue;
    }

    processed.push({
      type,
      text,
      ...(type === "bullet" && marker ? { marker } : {}),
    });
  }

  return processed;
}

function shouldPromoteParagraphBufferToBullets(lines) {
  if (lines.length < 2 || lines.length > 8) {
    return false;
  }

  return lines.every((line) => {
    const clean = normalizeWhitespace(line);
    const wordCount = getWordCount(clean);

    return (
      clean &&
      wordCount <= 8 &&
      clean.length <= 72 &&
      !/[.?!:]$/.test(clean) &&
      !looksCodeLike(clean)
    );
  });
}

function inferDocumentTitle(document) {
  const firstPage = document.pages?.[0];
  if (!firstPage) {
    return buildFallbackTitle(document.fileName);
  }

  const titleCandidate = [...(firstPage.readingItems || [])]
    .filter((item) => item.type === "line")
    .sort((left, right) => right.y - left.y)
    .find((line) => {
      const text = normalizeWhitespace(line.text);
      return (
        text &&
        !looksAutoGeneratedTitle(text) &&
        !looksCodeLike(text) &&
        getWordCount(text) <= 8 &&
        line.y >= firstPage.height * 0.8 &&
        isLikelyCenteredLine(line, firstPage)
      );
    });

  if (titleCandidate) {
    return normalizeWhitespace(titleCandidate.text);
  }

  return buildFallbackTitle(document.fileName);
}

function createImageBlock(image) {
  return {
    type: "image",
    image,
  };
}

function collectDocumentImagesWithProgress(document) {
  const readingItems = document.readingItems || [];
  const totalTextItems =
    readingItems.filter((item) => item.type === "line" && normalizeWhitespace(item.text))
      .length || 1;
  const images = [];
  let textSeen = 0;

  for (const item of readingItems) {
    if (item.type === "line") {
      if (normalizeWhitespace(item.text)) {
        textSeen += 1;
      }
      continue;
    }

    if (item.type === "image") {
      images.push({
        ...item,
        textProgress: textSeen / totalTextItems,
      });
    }
  }

  return images;
}

function countTextBlocks(blocks) {
  return blocks.reduce(
    (count, block) => count + (block.type === "image" ? 0 : 1),
    0,
  );
}

function findInsertionIndexByTextCount(blocks, targetTextCount, minimumIndex = 0) {
  if (targetTextCount <= 0) {
    return minimumIndex;
  }

  let textSeen = 0;
  for (let index = 0; index < minimumIndex; index += 1) {
    if (blocks[index].type !== "image") {
      textSeen += 1;
    }
  }

  if (targetTextCount <= textSeen) {
    return minimumIndex;
  }

  for (let index = minimumIndex; index < blocks.length; index += 1) {
    if (blocks[index].type !== "image") {
      textSeen += 1;
    }

    if (textSeen >= targetTextCount) {
      return index + 1;
    }
  }

  return blocks.length;
}

function mergeImagesIntoBlocks(blocks, document) {
  const images = collectDocumentImagesWithProgress(document);
  if (!images.length) {
    return blocks;
  }

  if (!blocks.length) {
    return images.map(createImageBlock);
  }

  const mergedBlocks = [...blocks];
  const textBlockCount = countTextBlocks(blocks);
  let minimumIndex = 0;
  let previousTarget = 0;

  for (const image of images) {
    const targetTextCount = Math.max(
      previousTarget,
      Math.round(image.textProgress * textBlockCount),
    );
    const insertionIndex = findInsertionIndexByTextCount(
      mergedBlocks,
      targetTextCount,
      minimumIndex,
    );

    mergedBlocks.splice(insertionIndex, 0, createImageBlock(image));
    minimumIndex = insertionIndex + 1;
    previousTarget = targetTextCount;
  }

  return mergedBlocks;
}

function buildFallbackTitle(fileName) {
  const titleSource = String(fileName || "")
    .replace(/\.(pdf|png|jpe?g)$/i, "")
    .replace(/\s+\(\d+\)\s*$/, "");

  return looksAutoGeneratedTitle(titleSource) ? "" : toSentenceCase(titleSource);
}

function normalizeOcrTranscription(text) {
  return String(text || "")
    .replace(/\r\n/g, "\n")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function createSyntheticLinesFromImage(image, pageHeight) {
  const transcription = normalizeOcrTranscription(image?.ocr?.transcription);
  if (!transcription) {
    return [];
  }

  const paragraphs = transcription
    .split(/\n\s*\n/)
    .map((paragraph) =>
      paragraph
        .split("\n")
        .map((line) => normalizeWhitespace(line))
        .filter(Boolean),
    )
    .filter((paragraph) => paragraph.length);
  if (!paragraphs.length) {
    return [];
  }

  const lineCount = paragraphs.reduce(
    (total, paragraph) => total + paragraph.length,
    0,
  );
  const fontSize = Math.max(
    8,
    Math.min(10.5, image.displayHeight / Math.max(lineCount * 1.45, 2)),
  );
  const lineStep = fontSize * 1.3;
  const paragraphGap = fontSize * 0.7;
  const lines = [];
  let currentY = image.y;

  for (const paragraph of paragraphs) {
    for (const text of paragraph) {
      lines.push({
        type: "line",
        text,
        pageNumber: image.pageNumber,
        x: image.x,
        endX: image.endX,
        y: currentY,
        top: pageHeight - currentY,
        fontSize,
        height: fontSize,
        isBold: false,
        isItalic: false,
        source: "image-ocr",
        sourceImageId: image.id,
      });
      currentY -= lineStep;
    }

    currentY -= paragraphGap;
  }

  return lines;
}

function buildPlainTextFromPages(pages) {
  const pageSections = pages.map((page) => {
    const parts = [];
    let previousLine;

    for (const item of page.readingItems || []) {
      if (item.type !== "line") {
        continue;
      }

      const text = normalizeWhitespace(item.text);
      if (!text) {
        continue;
      }

      if (!previousLine) {
        parts.push(text);
        previousLine = item;
        continue;
      }

      const verticalGap = Math.abs(previousLine.y - item.y);
      const paragraphBreak = verticalGap > previousLine.fontSize * 1.65;
      parts.push(paragraphBreak ? `\n\n${text}` : `\n${text}`);
      previousLine = item;
    }

    return normalizeWhitespace(parts.join(""));
  });

  return normalizeWhitespace(pageSections.filter(Boolean).join("\n\n"));
}

function enrichDocumentWithImageOcr(document, ocrEntries) {
  const ocrById = new Map(ocrEntries.map((entry) => [entry.id, entry]));

  const pages = document.pages.map((page) => {
    const readingItems = [];

    for (const item of page.readingItems || []) {
      if (item.type !== "image") {
        readingItems.push(item);
        continue;
      }

      const ocr = ocrById.get(item.id);
      const image = ocr ? { ...item, ocr } : item;

      if (ocr?.useAsText) {
        readingItems.push(...createSyntheticLinesFromImage(image, page.height));
      }

      if (ocr?.keepImage !== false) {
        readingItems.push(image);
      }
    }

    const pageImages = readingItems.filter((item) => item.type === "image");

    return {
      ...page,
      images: pageImages,
      readingItems,
    };
  });

  const readingItems = pages.flatMap((page) => page.readingItems || []);
  const images = readingItems.filter((item) => item.type === "image");

  return {
    ...document,
    pages,
    images,
    readingItems,
    plainText: buildPlainTextFromPages(pages),
    ocr: {
      processedCount: ocrEntries.length,
      usedAsTextCount: ocrEntries.filter((entry) => entry.useAsText).length,
      keptImageCount: ocrEntries.filter((entry) => entry.keepImage !== false).length,
    },
  };
}

function buildMeta({ blocks, document, fallbackReason, imageOcrWarning, usedGemini }) {
  return {
    imageCount: blocks.filter((block) => block.type === "image").length,
    usedGemini,
    usedImageOcr: Boolean(document.ocr?.processedCount),
    ocrImagesProcessed: document.ocr?.processedCount || 0,
    ocrTextImages: document.ocr?.usedAsTextCount || 0,
    preservedImages: document.ocr?.keptImageCount || document.images?.length || 0,
    imageOcrWarning: imageOcrWarning || null,
    fallbackReason: fallbackReason || null,
  };
}

function fallbackStructure(document, profile, options = {}) {
  const blocks = [];
  const title = inferDocumentTitle(document);
  const normalizedTitle = normalizeCompareText(title);
  let paragraphBuffer = [];

  function flushParagraph() {
    if (!paragraphBuffer.length) {
      return;
    }

    const lines = paragraphBuffer
      .map((line) => normalizeWhitespace(line))
      .filter(Boolean);
    if (shouldPromoteParagraphBufferToBullets(lines)) {
      for (const line of lines) {
        blocks.push({
          type: "bullet",
          text: line,
        });
      }
    } else {
      const text = normalizeWhitespace(lines.join(" "));
      if (text) {
        blocks.push({
          type: "paragraph",
          text,
        });
      }
    }

    paragraphBuffer = [];
  }

  for (const page of document.pages) {
    let previousLine;

    for (const item of page.readingItems || []) {
      if (item.type === "image") {
        flushParagraph();
        blocks.push(createImageBlock(item));
        previousLine = undefined;
        continue;
      }

      const text = normalizeWhitespace(item.text);
      if (!text) {
        continue;
      }

      if (
        page.pageNumber === 1 &&
        normalizedTitle &&
        normalizeCompareText(text) === normalizedTitle
      ) {
        previousLine = undefined;
        continue;
      }

      const verticalGap = previousLine ? Math.abs(previousLine.y - item.y) : 0;
      const forceBreak =
        previousLine &&
        verticalGap > previousLine.fontSize * profile.heuristics.paragraphBreakMultiplier;

      if (forceBreak) {
        flushParagraph();
      }

      if (isLikelyBullet(text)) {
        const listItem = extractListItem(text);
        flushParagraph();
        blocks.push({
          type: "bullet",
          text: listItem.text,
          ...(listItem.marker ? { marker: listItem.marker } : {}),
        });
        previousLine = item;
        continue;
      }

      const headingType = classifyHeadingLine(item, page, profile);
      if (headingType) {
        flushParagraph();
        blocks.push({
          type: headingType,
          text,
        });
        previousLine = item;
        continue;
      }

      paragraphBuffer.push(text);
      previousLine = item;
    }

    flushParagraph();
  }

  const normalizedBlocks = postProcessBlocks(blocks, profile);

  return {
    title,
    blocks: normalizedBlocks,
    meta: buildMeta({
      blocks: normalizedBlocks,
      document,
      fallbackReason: options.fallbackReason || "Gemini key not provided",
      imageOcrWarning: options.imageOcrWarning || "",
      usedGemini: false,
    }),
  };
}

function sanitizeStructuredResult(result, fallbackTitle, profile) {
  let title = normalizeWhitespace(result?.title) || fallbackTitle;
  const blocks = postProcessBlocks(result?.blocks, profile);

  if (!blocks.length) {
    throw new Error("Structured result did not include any blocks");
  }

  if (looksAutoGeneratedTitle(title)) {
    title = "";
  }

  const firstTextIndex = blocks.findIndex((block) => block.type !== "image");
  if (
    title &&
    firstTextIndex >= 0 &&
    normalizeCompareText(blocks[firstTextIndex].text) === normalizeCompareText(title)
  ) {
    blocks.splice(firstTextIndex, 1);
  }

  return {
    title,
    blocks,
  };
}

async function enrichDocumentIfPossible({ apiKey, customInstructions, document }) {
  if (!apiKey || !document.images?.length) {
    return {
      document,
      imageOcrWarning: "",
    };
  }

  try {
    const ocrEntries = await extractImageTextWithGemini({
      images: document.images,
      apiKey,
      customInstructions,
    });

    return {
      document: enrichDocumentWithImageOcr(document, ocrEntries),
      imageOcrWarning: "",
    };
  } catch (error) {
    return {
      document,
      imageOcrWarning: error.message,
    };
  }
}

export async function structureDocument({
  document,
  profile,
  apiKey,
  customInstructions,
}) {
  const enriched = await enrichDocumentIfPossible({
    apiKey,
    customInstructions,
    document,
  });
  const workingDocument = enriched.document;
  const fallbackReason = apiKey
    ? workingDocument.plainText
      ? "Gemini structuring unavailable"
      : "No extractable text found; preserved images instead"
    : "Gemini key not provided";
  const fallback = fallbackStructure(workingDocument, profile, {
    fallbackReason,
    imageOcrWarning: enriched.imageOcrWarning,
  });

  if (!apiKey || !workingDocument.plainText) {
    return fallback;
  }

  try {
    const structuredResult = await structureWithGemini({
      rawText: workingDocument.plainText,
      profile,
      fallbackTitle: fallback.title,
      apiKey,
      customInstructions,
    });
    const sanitized = sanitizeStructuredResult(
      structuredResult,
      fallback.title,
      profile,
    );
    const blocks = mergeImagesIntoBlocks(sanitized.blocks, workingDocument);

    return {
      ...sanitized,
      blocks,
      meta: buildMeta({
        blocks,
        document: workingDocument,
        fallbackReason: null,
        imageOcrWarning: enriched.imageOcrWarning,
        usedGemini: true,
      }),
    };
  } catch (error) {
    return {
      ...fallback,
      meta: {
        ...fallback.meta,
        usedGemini: false,
        fallbackReason: error.message,
      },
    };
  }
}
